env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      before_install:
        - gem install xcpretty
      script:
        - swift build
        - swift run lite-test
        - swift test 2>&1 | xcpretty && exit ${PIPESTATUS[0]}
    - os: linux
      language: generic
      rvm:
        - 2.2
        - jruby
        - 2.0.0-p247
      sudo: required
      dist: trusty
      before_install:
        - gem install xcpretty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift build
        - swift run lite-test
        - swift test 2>&1 | xcpretty && exit ${PIPESTATUS[0]}
